#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec  6 10:29:01 2019
@author: thomasdyra
"""

from bs4 import BeautifulSoup 
import requests
import time
import pandas as pd
import matplotlib.pyplot as plt

def top_box_office():
 
    url = "https://www.rottentomatoes.com/browse/box-office/"
    
    response = requests.get(url)
    
    html_doc = response.text
    
    soup = BeautifulSoup(html_doc, "lxml")
    
    table = soup.find('table', class_='center table')
    table_rows = table.find_all('tr', itemprop='itemListElement')
    row =[]
    for tr in table_rows:
        td = tr.find_all('td')
        row.append([i.text for i in td])
    time.sleep(3)

    return row


def create_dataframe(list):
    for i in list:
       
        dataframe_= pd.DataFrame(list[0:], columns=list[0])
        dataframe_.columns = ['this week', 'lastweek', 't_meter', 'title', 'weeks released','weekend gross','total gross', 'theater avg', '# of theater']
        
        
        
    return dataframe_


def clean_dataframe(y):
    columns = y.columns
    y[columns] = y[columns].replace({'%':''}, regex = True)
    y[columns] = y[columns].replace({'No Score Yet':'0'}, regex = True)

    return y 


def numeric_data(f):
    t=f.t_meter
    j=pd.to_numeric(t, errors = 'ignore', downcast = 'integer')
    
    return j


def fresh_movies(j):
   
    
    for i in j:
        if i >= 60:
            return (j)
    

    
    



x = top_box_office()
print(x)
y=create_dataframe(x)
print(y)


x = top_box_office()
print(x)
y=create_dataframe(x)
print(y)

f = clean_dataframe(y)
print(f)


j = numeric_data(f)
print(j)
j.plot()
j.plot(kind='bar', x = 'title', y = j)
h= fresh_movies(j)



